#!/usr/bin/env bash
# Write /opt/khelkhud/.env on the VM — the one place production secrets live.
#
# Run once at setup, and again whenever a secret changes. Deliberately interactive: this
# repo has no secret store, and the alternative (a committed encrypted file, or secrets
# passed as deploy.sh arguments) puts them in git history or shell history respectively.
#
# Values are read with `read -rs` where secret, and the assembled file is piped straight
# over SSH — it is never written to local disk.
#
# For anything beyond a one-person project, replace this with Azure Key Vault + a managed
# identity on the VM. It is not worth the $0.03/10k-operations and the extra moving part
# today, but that is the upgrade path.

source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

assert_azure_login

VM_IP="$(vm_public_ip)"
[[ -n "$VM_IP" ]] || die "VM ${VM_NAME} not found — run ./devops/provision-vm.sh first."

PG_HOST="$(az_cli postgres flexible-server show -g "$AZ_RG" -n "$PG_SERVER" \
  --query fullyQualifiedDomainName -o tsv 2>/dev/null || true)"
[[ -n "$PG_HOST" ]] || die "Flexible Server ${PG_SERVER} not found — run ./devops/provision-postgres.sh."

# The public origin the browser sees. With Caddy terminating on one hostname, WEB_URL and
# API_URL are the SAME value — the API is at /api/* on the same origin. That is what makes
# CORS a non-issue and the session cookie first-party.
if [[ -n "$DOMAIN" ]]; then
  PUBLIC_ORIGIN="https://${DOMAIN}"
else
  PUBLIC_ORIGIN="http://${VM_IP}"
  warn "DOMAIN unset — using ${PUBLIC_ORIGIN}. Re-run this script after khelkhud.org resolves,"
  warn "and update the Google OAuth redirect URI to match, or sign-in will fail."
fi

echo
info "Writing ${REMOTE_DIR}/.env on ${VM_IP}"
info "Public origin: ${PUBLIC_ORIGIN}"
echo

read -rsp "Postgres admin password for ${PG_ADMIN_USER}: " PG_PASSWORD; echo
[[ -n "$PG_PASSWORD" ]] || die "Password required."

read -rp  "Google OAuth client ID: " GOOGLE_CLIENT_ID
read -rsp "Google OAuth client secret: " GOOGLE_CLIENT_SECRET; echo
read -rp  "Admin emails (comma-separated) [${ADMIN_EMAIL}]: " ADMIN_EMAILS
ADMIN_EMAILS="${ADMIN_EMAILS:-$ADMIN_EMAIL}"

echo
info "Razorpay — leave blank to run payments in stub mode."
read -rp  "Razorpay key id: " RAZORPAY_KEY_ID
read -rsp "Razorpay key secret: " RAZORPAY_KEY_SECRET; echo
read -rsp "Razorpay webhook secret: " RAZORPAY_WEBHOOK_SECRET; echo

# 64 hex chars. config.ts enforces a 32-char minimum and refuses to boot below it.
SESSION_SECRET="$(openssl rand -hex 32)"

# DATABASE_URL notes:
#   sslmode=require — Flexible Server rejects unencrypted connections outright.
#   connection_limit=5 — B1ms allows ~50 connections total; the API, the migrate job and
#   a human with psql all share them, and Prisma's default pool is num_cpus*2+1, which on
#   a 2-vCPU box would be fine but leaves no headroom during a deploy overlap.
DATABASE_URL="postgresql://${PG_ADMIN_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DATABASE}?sslmode=require&connection_limit=5"

ssh_vm "umask 077 && mkdir -p ${REMOTE_DIR} && cat > ${REMOTE_DIR}/.env" <<EOF
# GENERATED by devops/bootstrap-env.sh — do not edit by hand unless you mean it.
# This file is the only copy of these secrets. It is not in git and not in any image.

NODE_ENV=production
DATABASE_URL=${DATABASE_URL}

API_PORT=4000
WEB_URL=${PUBLIC_ORIGIN}
API_URL=${PUBLIC_ORIGIN}

SESSION_SECRET=${SESSION_SECRET}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ADMIN_EMAILS=${ADMIN_EMAILS}

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}

# Uploads land on a docker volume on this VM (backed up nightly by devops/backup.sh).
# Switch to s3 only if you add an object store; there is no Azure Blob driver in the API.
STORAGE_DRIVER=local

# Email falls back to console logging while the AWS keys are blank, which is the correct
# state until SES production access is granted for the khelkhud.org domain.
MAIL_FROM=no-reply@${DOMAIN:-khelkhud.org}
AWS_REGION=ap-south-1
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
EOF

ssh_vm "chmod 600 ${REMOTE_DIR}/.env"

echo
ok "Wrote ${REMOTE_DIR}/.env (mode 600)"
cat <<EOF

Google OAuth — add this EXACT redirect URI to the Cloud Console client, or sign-in 400s:

    ${PUBLIC_ORIGIN}/api/auth/google/callback

And this authorised JavaScript origin:

    ${PUBLIC_ORIGIN}

Razorpay webhook URL:

    ${PUBLIC_ORIGIN}/api/webhooks/razorpay

Next: ./devops/deploy.sh
EOF
