import Image from "next/image";
import Link from "next/link";
import { formatPaise } from "@khelkhud/shared";
import { Button } from "@/components/ui/button";
import { AthleteCard, type AthleteCardData } from "@/components/athlete-card";
import { Horizon } from "@/components/horizon";
import { KitCosts } from "@/components/landing/kit-costs";
import { FaqSection } from "@/components/landing/faq-section";
import { FaqJsonLd } from "@/components/seo/faq-jsonld";
import { FAQS } from "@/lib/faq";
import { Reveal } from "@/components/reveal";
import { apiServer } from "@/lib/api-server";

// Page structure (docs/brand-guidelines.md §2).
//
// The page opens IN the sunrise rather than before it — the hero illustration is already
// full of warm light, so the old night-to-day scroll no longer applies. The shape is now
// promise -> problem -> resolution:
//
//   cream hero      what this is, in plain words, over the illustration
//   cream-2 ticker
//   predawn gap     the one dark band: what is actually stopping these athletes
//   first light     the marigold moment — someone funds it
//   cream daylight  how it works, the receipts, the athletes
//   predawn close   night again, and tomorrow morning
//
// The dark band earns its darkness by being the section about the problem. Do not add a
// second one; two makes the page stripy and the contrast stops meaning anything.
//
// The narrative uses ONE composite athlete — a javelin thrower from Nizamabad with an
// ₹18,400 request — carried from the gap section through to the receipts, so the
// abstract claim ("we track every rupee") is answered by a concrete number the reader
// already met. She is explicitly labelled as illustrative wherever a figure is shown.

const TICKER = [
  "Athletics", "Kabaddi", "Boxing", "Badminton", "Wrestling", "Shooting",
  "Weightlifting", "Hockey", "Nizamabad", "Warangal", "Karimnagar", "Khammam",
  "Adilabad", "Mahbubnagar", "Hyderabad",
];

const STEPS = [
  {
    n: "01",
    title: "Discover",
    body: "Browse athletes by sport, district, age group and what they actually need. Every profile is checked by a person — ID, achievements, coach — before it goes live.",
  },
  {
    n: "02",
    title: "Sponsor",
    body: "Fund one specific line item, not a vague cause. ₹2,000 for a month of coaching is a real sponsorship here, and it goes to a named request.",
  },
  {
    n: "03",
    title: "Track",
    body: "Watch the money get spent. Each allocation moves from planned to purchased to completed, and the receipt is attached to the one it paid for.",
  },
  {
    n: "04",
    title: "Impact",
    body: "Get the athlete's own updates — the meet, the timing, the result, the photo. You will know whether it worked, which is the part nobody usually tells you.",
  },
];

const ATHLETE_STEPS = [
  {
    t: "Tell us who you are",
    d: "Sport, age group, district, coach, and your achievements so far. Upload one ID proof and whatever certificates you have.",
  },
  {
    t: "Get verified",
    d: "A person reviews it. If something is missing we ask for it rather than rejecting you. Verified profiles are the only ones sponsors see.",
  },
  {
    t: "Post what you need",
    d: "Break it into real items with real prices — the shoes, the fees, the bus ticket. Vague asks do not get funded; itemised ones do.",
  },
  {
    t: "Show what happened",
    d: "Upload receipts as you spend, and post updates after the meet. Sponsors who see the result come back for the next request.",
  },
];

// The worked example. Figures are illustrative and labelled as such on the page.
const LEDGER = [
  { label: "Competition javelin (700g)", paise: 780000, status: "COMPLETED" },
  { label: "Spikes, correct size", paise: 420000, status: "COMPLETED" },
  { label: "Coaching — 3 months", paise: 450000, status: "PURCHASED" },
  { label: "Travel to Nationals, Ranchi", paise: 190000, status: "PLANNED" },
];
const LEDGER_TOTAL = LEDGER.reduce((sum, row) => sum + row.paise, 0);

const STATUS_STYLE: Record<string, string> = {
  COMPLETED: "bg-ground/10 text-ground",
  PURCHASED: "bg-marigold/15 text-[#8A4E12]",
  PLANNED: "bg-sweat/12 text-slate",
};
const STATUS_LABEL: Record<string, string> = {
  COMPLETED: "Receipt filed",
  PURCHASED: "Purchased",
  PLANNED: "Planned",
};

export default async function HomePage() {
  const featuredRes = await apiServer<{ data: AthleteCardData[] }>("/api/athletes?pageSize=3");
  const featured = featuredRes?.data ?? [];

  return (
    <>
      <FaqJsonLd faqs={FAQS} />

      {/* ── the hero ───────────────────────────────────────────────────────── */}
      {/* The illustration does the arguing: a barefoot batter hitting a six with a taped
          plank, through someone's window. Nobody needs a metaphor explained to them after
          seeing that, so the copy is deliberately plain — it says what the site does and
          gets out of the way.
          Generated by devops/generate-brand-images.ts (spec key: hero-six). The prompt
          reserves the LEFT third as empty sky, which is where this text sits. */}
      <section className="relative isolate overflow-hidden bg-cream">
        {/* md and up: the illustration is the background, text over its empty left third.
            Below md it is NOT a background — see the inline block further down. Overlaying
            it on a phone crops the scene to a torso, so the story becomes unreadable at
            exactly the same moment the body copy loses its contrast against the figure. */}
        <div className="pointer-events-none absolute inset-0 -z-10 hidden md:block">
          <Image
            src="/brand/hero-six.png"
            alt=""
            aria-hidden
            fill
            priority
            sizes="100vw"
            // Held right-of-centre so the batter and the cracked window stay in frame as
            // the viewport narrows; the empty sky the text needs is on the left.
            className="object-cover object-[72%_center]"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-cream via-cream/72 to-cream/10" />
          {/* Settles the image into the band below instead of cutting it off mid-scene. */}
          <div className="absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-cream to-transparent" />
        </div>

        <div className="mx-auto flex w-full max-w-6xl flex-col justify-center px-6 pb-14 pt-24 sm:pt-28 md:min-h-[clamp(36rem,86svh,50rem)] md:pt-32">
          <div className="max-w-2xl">
            <p className="eyebrow text-slate">Sports sponsorship in Telangana</p>
            {/* The second clause has to carry ambition, not reassurance. "See every rupee"
                answered a question nobody has asked yet at the top of the page — it is a
                trust argument, and trust arguments belong after the aspiration, not
                instead of it. Transparency now lives in the subhead and the stat row,
                where it reads as proof rather than as the pitch. */}
            {/* Two lines on desktop, broken at the sentence — not by measure.
                Narrowing the max-width would have produced MORE lines, not fewer, and
                widening it to fit line one on a single row pushed the text out over the
                batter. So the size steps down from `text-display` to a ceiling that fits
                "Back a young athlete." inside the 42rem text column (~21 characters at
                62px), and the break is placed explicitly.
                Below md the span goes inline again and wraps naturally: forcing the break
                on a phone leaves "go." orphaned on a fourth line. */}
            <h1 className="mt-5 text-[clamp(2.6rem,4.6vw,3.9rem)] font-semibold leading-[1.05] tracking-[-0.02em] text-ink">
              Back a young athlete.{" "}
              <span className="md:block">See how far they go.</span>
            </h1>
            <p className="mt-6 max-w-lg text-lg leading-relaxed text-slate">
              Across Telangana, talented athletes are competing without proper kit,
              coaching or travel money. Pick one, pay for one specific thing they need,
              and follow every rupee of it to the finish line.
            </p>
            <div className="mt-9 flex flex-wrap items-center gap-3">
              <Button asChild size="hero" variant="accent">
                <Link href="/athletes">Find an athlete</Link>
              </Button>
              <Button asChild size="hero" variant="onLight" className="border">
                <Link href="/login">I&rsquo;m an athlete</Link>
              </Button>
            </div>
          </div>

          {/* Below md the illustration lives here, full width and uncropped, so the whole
              scene reads: the bat, the ball, the window. Bleeds past the page gutter. */}
          <div className="-mx-6 mt-10 md:hidden">
            <Image
              src="/brand/hero-six.png"
              alt="A young batter, barefoot and without pads, hitting a six with a taped wooden plank on a dusty maidan at sunrise — the ball arcing away and a window cracked behind him"
              width={1536}
              height={1024}
              priority
              sizes="100vw"
              className="w-full"
            />
          </div>

          {/* max-w-2xl, not 3xl: on desktop these sit over the illustration, and the third
              column was drifting past the scrim onto bare sunlit sand. */}
          <div className="mt-12 grid max-w-2xl gap-6 sm:grid-cols-3 md:mt-14">
            {[
              { k: "₹2,000", v: "is a real sponsorship here — about a month of coaching." },
              { k: "Every rupee", v: "is itemised, and every item ends in an uploaded receipt." },
              { k: "33 districts", v: "of Telangana, not just the city." },
            ].map((s) => (
              <div key={s.k} className="border-t border-ink/15 pt-4">
                <p className="font-display text-xl font-semibold text-ink" data-numeric>
                  {s.k}
                </p>
                <p className="mt-1.5 text-sm leading-relaxed text-slate">{s.v}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Ticker — sports and districts, the breadth of the thing. */}
      <div className="border-y border-border bg-cream-2 py-4">
        {/* Wraps rather than truncating: at 1440px a single nowrap line loses the last
            three districts to an ellipsis, which is precisely the wrong impression. */}
        <ul className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-x-5 gap-y-1.5 px-6">
          {TICKER.map((item) => (
            <li key={item} className="eyebrow text-slate/70">
              {item}
            </li>
          ))}
        </ul>
      </div>

      {/* ── the gap · still dark ───────────────────────────────────────────── */}
      <section className="dawn-wash relative overflow-hidden">
        <div className="mx-auto max-w-6xl px-6 py-24 sm:py-32">
          <Reveal>
            <p className="eyebrow text-marigold">The gap</p>
            <h2 className="mt-4 max-w-[18ch] text-h1 font-semibold text-cream">
              India does not have a talent problem.
            </h2>
          </Reveal>

          <Reveal delay={80}>
            <div className="mt-14 grid gap-12 border-t border-cream/12 pt-12 sm:grid-cols-2 sm:gap-20">
              <div>
                <p className="eyebrow text-cream/40">What there is plenty of</p>
                <p className="mt-4 font-display text-2xl leading-snug text-cream">Potential.</p>
                <p className="mt-4 max-w-md leading-relaxed text-cream/65">
                  Distributed evenly across every district, every income bracket, every
                  government school with a patch of ground behind it. It shows up at 5am
                  whether or not anyone is funding it.
                </p>
              </div>
              <div>
                <p className="eyebrow text-cream/40">What there isn&rsquo;t</p>
                <p className="mt-4 font-display text-2xl leading-snug text-marigold-light">
                  Resources.
                </p>
                <p className="mt-4 max-w-md leading-relaxed text-cream/65">
                  Which are not distributed evenly at all. A competition javelin costs more
                  than a month of household income in most of the districts our athletes
                  come from. Careers end over four-figure sums.
                </p>
              </div>
            </div>
          </Reveal>

          <Reveal delay={120}>
            <p className="mx-auto mt-20 max-w-3xl text-center font-display text-2xl leading-snug text-cream sm:text-3xl">
              khelkhud is not a fundraiser. It is the missing piece of infrastructure
              between the two.
            </p>
          </Reveal>

          {/* What they're working with, with the replacement cost written onto each object.
              The join between picture and price is the argument, so it happens in one
              element rather than across two blocks. */}
          <Reveal delay={140}>
            <div className="mt-16">
              <KitCosts />
            </div>
          </Reveal>

          {/* The request, itemised. The specificity is the argument. */}
          <Reveal delay={160}>
            <div className="mx-auto mt-12 max-w-2xl rounded-xl border border-cream/15 bg-predawn-lift/70 p-7 sm:p-9">
              <div className="flex flex-wrap items-baseline justify-between gap-3">
                <div>
                  <p className="eyebrow text-marigold">One request</p>
                  <p className="mt-2 font-display text-xl text-cream">
                    Javelin, Under 19 &mdash; Nizamabad
                  </p>
                </div>
                <p className="text-sm text-cream/45">Nationals in 11 weeks</p>
              </div>
              <ul className="mt-7 space-y-3.5">
                {LEDGER.map((row) => (
                  <li
                    key={row.label}
                    className="flex items-baseline justify-between gap-4 border-b border-cream/10 pb-3.5 text-sm last:border-0"
                  >
                    <span className="text-cream/75">{row.label}</span>
                    <span className="shrink-0 font-medium text-cream" data-numeric>
                      {formatPaise(row.paise)}
                    </span>
                  </li>
                ))}
              </ul>
              <div className="mt-7">
                <Horizon
                  raisedPaise={0}
                  totalPaise={LEDGER_TOTAL}
                  tone="dark"
                  label="Raised so far"
                />
              </div>
              <p className="mt-5 text-xs leading-relaxed text-cream/40">
                Illustrative example. Real requests are written by the athlete and
                verified before they appear.
              </p>
            </div>
          </Reveal>
        </div>
      </section>

      {/* ── first light · the marigold moment ──────────────────────────────── */}
      {/* Starts on predawnLift, exactly where `dawn-wash` above it ended, so the join is
          invisible and the sunrise reads as continuous rather than as a new section. */}
      <section className="dawn-first-light relative overflow-hidden">
        <div className="relative mx-auto max-w-3xl px-6 py-24 text-center sm:py-28">
          <Reveal>
            <p className="eyebrow text-cream/60">First light</p>
            <h2 className="mt-5 font-display text-h1 font-semibold text-cream">
              Then one person says yes.
            </h2>
            <p className="mx-auto mt-6 max-w-xl leading-relaxed text-cream/80">
              Fourteen minutes on a phone during a lunch break. Not a campaign, not a gala,
              not a form in triplicate &mdash; one sponsor picking one line item off one
              athlete&rsquo;s list and paying for it.
            </p>
            <div className="mx-auto mt-12 max-w-md">
              <Horizon
                raisedPaise={LEDGER_TOTAL}
                totalPaise={LEDGER_TOTAL}
                tone="dark"
                label="Fully funded"
              />
            </div>
          </Reveal>
        </div>
      </section>

      {/* ── daylight · how it works ────────────────────────────────────────── */}
      <section id="how-it-works" className="bg-cream-2">
        <div className="mx-auto max-w-6xl px-6 py-24 sm:py-28">
          <Reveal>
            <p className="eyebrow text-slate">A sponsorship, end to end</p>
            <h2 className="mt-4 max-w-[20ch] text-h1 font-semibold">
              Four steps, and you can see all of them.
            </h2>
          </Reveal>
          <div className="mt-16 grid gap-x-10 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">
            {STEPS.map((step, i) => (
              <Reveal key={step.n} delay={i * 70}>
                <div className="border-t-2 border-ink/12 pt-5">
                  <p className="eyebrow text-marigold" data-numeric>
                    {step.n}
                  </p>
                  <h3 className="mt-3 font-display text-h3 font-semibold">{step.title}</h3>
                  <p className="mt-3 text-sm leading-relaxed text-slate">{step.body}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ── the proof · the receipts ───────────────────────────────────────── */}
      <section id="proof" className="bg-background">
        <div className="mx-auto max-w-6xl px-6 py-24 sm:py-28">
          <div className="grid items-start gap-14 lg:grid-cols-[1fr_1.15fr] lg:gap-20">
            <Reveal>
              <p className="eyebrow text-slate">The proof</p>
              <h2 className="mt-4 text-h1 font-semibold">
                You will know where every rupee went.
              </h2>
              <p className="mt-6 max-w-md leading-relaxed text-slate">
                Most giving ends at the payment confirmation. Here it starts there. Your
                sponsorship is split into the items it was meant to buy, and each one moves
                through planned &rarr; purchased &rarr; completed with the receipt attached
                to it.
              </p>
              <p className="mt-4 max-w-md leading-relaxed text-slate">
                If an item stalls, you see that too. Transparency that only shows good news
                is marketing, not accounting.
              </p>
              <Button asChild size="hero" variant="accent" className="mt-9">
                <Link href="/athletes">Browse open requests</Link>
              </Button>
            </Reveal>

            {/* The allocation ledger — the same ₹18,400 from the hero, now spent. */}
            <Reveal delay={90}>
              <div className="overflow-hidden rounded-xl border border-border bg-card shadow-long">
                <div className="flex items-baseline justify-between gap-4 border-b border-border px-6 py-5">
                  <div>
                    <p className="eyebrow text-slate">Sponsorship</p>
                    <p className="mt-1.5 font-mono text-sm text-foreground">KK-2026-0417</p>
                  </div>
                  <p className="font-display text-xl font-semibold" data-numeric>
                    {formatPaise(LEDGER_TOTAL)}
                  </p>
                </div>
                <ul>
                  {LEDGER.map((row) => (
                    <li
                      key={row.label}
                      className="flex flex-wrap items-center justify-between gap-x-4 gap-y-2 border-b border-border px-6 py-4 last:border-0"
                    >
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium">{row.label}</p>
                        <span
                          className={`mt-1.5 inline-block rounded-full px-2.5 py-0.5 text-[0.6875rem] font-medium ${STATUS_STYLE[row.status]}`}
                        >
                          {STATUS_LABEL[row.status]}
                        </span>
                      </div>
                      <p className="text-sm font-semibold" data-numeric>
                        {formatPaise(row.paise)}
                      </p>
                    </li>
                  ))}
                </ul>
                <div className="bg-cream-2 px-6 py-5">
                  <Horizon
                    raisedPaise={LEDGER.filter((r) => r.status === "COMPLETED").reduce(
                      (s, r) => s + r.paise,
                      0,
                    )}
                    totalPaise={LEDGER_TOTAL}
                    label="Spent and receipted"
                  />
                  <p className="mt-4 text-xs leading-relaxed text-sweat">
                    Illustrative. In a live sponsorship each row links to the uploaded
                    receipt and the athlete&rsquo;s update about it.
                  </p>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* ── the athletes ───────────────────────────────────────────────────── */}
      {featured.length > 0 ? (
        <section className="border-y border-border bg-cream-2">
          <div className="mx-auto max-w-6xl px-6 py-24 sm:py-28">
            <Reveal>
              <div className="flex flex-wrap items-end justify-between gap-6">
                <div>
                  <p className="eyebrow text-slate">Open right now</p>
                  <h2 className="mt-4 max-w-[18ch] text-h2 font-semibold">
                    Athletes waiting on one specific thing.
                  </h2>
                </div>
                <Button asChild variant="outline" size="lg">
                  <Link href="/athletes">See all athletes &rarr;</Link>
                </Button>
              </div>
            </Reveal>
            <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {featured.map((a, i) => (
                <Reveal key={a.id} delay={i * 70}>
                  <AthleteCard athlete={a} />
                </Reveal>
              ))}
            </div>
          </div>
        </section>
      ) : null}

      {/* ── for athletes ───────────────────────────────────────────────────── */}
      {/* Two rows, not two columns. As a single 1fr/1fr grid the left held a heading, a
          paragraph and a button while the right held an image plus four steps — so the
          left ran out after a third of the height and the section had a column of dead
          space down its whole left side. Pitch and image balance each other on row one;
          the steps span the full width beneath. */}
      <section id="athletes" className="bg-background">
        <div className="mx-auto max-w-6xl px-6 py-24 sm:py-28">
          <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-16">
            <Reveal>
              <p className="eyebrow text-slate">For athletes</p>
              <h2 className="mt-4 text-h1 font-semibold">
                If you&rsquo;re the one on the ground at five.
              </h2>
              <p className="mt-6 max-w-md leading-relaxed text-slate">
                You do not need a manager, a federation contact, or a viral video. You need
                a profile that is true, and a list of what is actually stopping you. Put a
                number on it. That is the whole ask.
              </p>
              <Button asChild size="hero" variant="accent" className="mt-9">
                <Link href="/login">Create your athlete profile</Link>
              </Button>
            </Reveal>
            <Reveal delay={90}>
              {/* Generated (spec key: barefoot-sprint). Squared-off corners: the brand
                  keeps photographic radius at 4px because roundness reads as UI chrome,
                  and these are people (brand doc §5). */}
              <Image
                src="/brand/barefoot-sprint.png"
                alt="A young sprinter mid-stride, barefoot, on a chalk-marked red-earth track at dawn, casting a long shadow"
                width={1024}
                height={1024}
                sizes="(max-width: 1024px) 92vw, 32rem"
                className="w-full rounded-[4px]"
              />
            </Reveal>
          </div>

          <ol className="mt-20 grid gap-x-12 gap-y-10 sm:grid-cols-2">
            {ATHLETE_STEPS.map((item, i) => (
              <Reveal as="li" key={item.t} delay={i * 60}>
                <div className="flex gap-5 border-t-2 border-ink/12 pt-5">
                  <span
                    className="font-display text-lg font-semibold text-marigold"
                    data-numeric
                  >
                    0{i + 1}
                  </span>
                  <div>
                    <p className="font-display text-h3 font-semibold">{item.t}</p>
                    <p className="mt-2 text-sm leading-relaxed text-slate">{item.d}</p>
                  </div>
                </div>
              </Reveal>
            ))}
          </ol>
        </div>
      </section>

      <FaqSection />

      {/* ── night again · the close ────────────────────────────────────────── */}
      <section className="dawn-dusk relative overflow-hidden">
        <div className="mx-auto max-w-3xl px-6 py-24 text-center sm:py-32">
          <Reveal>
            <h2 className="font-display text-h1 font-semibold text-cream">
              Tomorrow morning, she will be on that ground again.
            </h2>
            <p className="mx-auto mt-6 max-w-xl leading-relaxed text-cream/70">
              That part is not in question and never was. Whether she is in shoes that fit
              is the part you can change.
            </p>
            <div className="mt-11 flex flex-wrap items-center justify-center gap-4">
              <Button asChild size="hero" variant="accent">
                <Link href="/athletes">Back an athlete</Link>
              </Button>
              <Button asChild size="hero" variant="onDark" className="border">
                <Link href="/login">I&rsquo;m an athlete</Link>
              </Button>
            </div>
          </Reveal>
        </div>
      </section>
    </>
  );
}
