import {
  app,
  brand,
  dawn,
  firstlight,
  fonts,
  leading,
  radius,
  scrim,
  shadow,
  statusColors,
  type,
} from './tokens.js';

// Emits each brand system as a shadcn/ui-convention CSS contract. Both files are
// imported by the single Next.js app (admin lives at /admin — no separate app):
//
//   firstlight.css — :root variables (the site default) + the Tailwind v4 `@theme`
//                    blocks that mint the brand utilities (bg-predawn, text-marigold,
//                    font-display, …) and the `@theme inline` indirection for shadcn.
//   app.css        — the SAME variable names redefined under `.theme-app`, applied by
//                    the dashboard/admin layout wrappers, so `bg-background` resolves
//                    to app values inside those subtrees and firstlight everywhere else.
//
// That scoping is what makes the brand's never-mix-the-systems rule structural rather
// than a thing reviewers have to remember.

function block(vars: Record<string, string>, indent = '  '): string {
  return Object.entries(vars)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join('\n');
}

const statusVars = Object.fromEntries(
  Object.entries(statusColors).map(([k, v]) => [
    `--status-${k.toLowerCase().replace(/_/g, '-')}`,
    v,
  ]),
);

// Brand DNA + motif variables. Identical in both systems — they are the brand, not the
// system. The app system simply uses fewer of them.
const brandVars: Record<string, string> = {
  '--kk-nightfall': brand.nightfall,
  '--kk-predawn': brand.predawn,
  '--kk-predawn-lift': brand.predawnLift,
  '--kk-marigold': brand.marigold,
  '--kk-marigold-light': brand.marigoldLight,
  '--kk-ground': brand.ground,
  '--kk-clay': brand.clay,
  '--kk-cream': firstlight.cream,
  '--kk-cream-2': firstlight.cream2,
  '--kk-ink': firstlight.ink,
  '--kk-slate': firstlight.slate,
  '--kk-border-dark': firstlight.borderDark,
  '--kk-scrim-top': scrim.top,
  '--kk-scrim-bottom': scrim.bottom,
  '--kk-scrim-full': scrim.full,
  '--kk-dawn-sky': dawn.sky,
  '--kk-dawn-wash': dawn.wash,
  '--kk-dawn-dusk': dawn.dusk,
  '--kk-dawn-first-light': dawn.firstLight,
  '--kk-horizon': dawn.horizon,
  '--kk-horizon-glow': dawn.horizonGlow,
  '--kk-shadow-long': shadow.long,
  '--kk-shadow-lift': shadow.lift,
};

const HEADER = (file: string) =>
  `/* GENERATED by @khelkhud/theme — do not edit.
   Source: packages/theme/src/tokens.ts  (brand: docs/brand-guidelines.md)
   Regenerate: pnpm --filter @khelkhud/theme build
   File: ${file} */`;

export function firstlightCss(): string {
  const root: Record<string, string> = {
    ...brandVars,
    // Font stacks. next/font sets these same variable names on <html>, which overrides
    // these declarations — the values here are the fallback stacks and the record of
    // what the brand actually specifies.
    '--kk-font-display': fonts.display,
    '--kk-font-sans': fonts.sans,
    '--kk-font-mono': fonts.mono,
    // Fluid type scale.
    '--kk-text-display': type.display,
    '--kk-text-h1': type.h1,
    '--kk-text-h2': type.h2,
    '--kk-text-h3': type.h3,
    '--kk-text-small': type.small,
    '--kk-text-eyebrow': type.eyebrow,
    '--kk-leading-display': leading.display,
    '--kk-leading-heading': leading.heading,
    '--kk-leading-body': leading.body,
    // shadcn contract — the firstlight system.
    '--background': firstlight.cream,
    '--foreground': firstlight.ink,
    '--card': '#FFFFFF',
    '--card-foreground': firstlight.ink,
    '--popover': '#FFFFFF',
    '--popover-foreground': firstlight.ink,
    '--primary': brand.predawn,
    '--primary-foreground': firstlight.cream,
    '--secondary': firstlight.cream2,
    '--secondary-foreground': firstlight.ink,
    '--muted': firstlight.cream2,
    '--muted-foreground': firstlight.slate,
    '--accent': firstlight.cream2,
    '--accent-foreground': firstlight.ink,
    '--destructive': brand.clay,
    '--destructive-foreground': firstlight.cream,
    '--border': firstlight.border,
    '--input': firstlight.border,
    '--ring': brand.marigold,
    '--radius': `${radius.card}px`,
    // shadcn sidebar contract. Unused on public surfaces but declared so a component
    // dropped onto a public page never renders unstyled.
    '--sidebar': brand.predawn,
    '--sidebar-foreground': firstlight.cream,
    '--sidebar-primary': brand.marigold,
    '--sidebar-primary-foreground': '#FFFFFF',
    '--sidebar-accent': app.sidebarHover,
    '--sidebar-accent-foreground': '#FFFFFF',
    '--sidebar-border': brand.nightfall,
    '--sidebar-ring': brand.marigold,
    ...statusVars,
  };

  return `${HEADER('firstlight.css')}
:root {
${block(root)}
}

/* Brand utilities. Literal values — these colours are the brand and never change per
   scope, so they resolve at build time rather than through a custom property. */
@theme {
  --color-nightfall: ${brand.nightfall};
  --color-predawn: ${brand.predawn};
  --color-predawn-lift: ${brand.predawnLift};
  --color-marigold: ${brand.marigold};
  --color-marigold-light: ${brand.marigoldLight};
  --color-ground: ${brand.ground};
  --color-clay: ${brand.clay};
  --color-cream: ${firstlight.cream};
  --color-cream-2: ${firstlight.cream2};
  --color-ink: ${firstlight.ink};
  --color-slate: ${firstlight.slate};
  --color-sweat: ${firstlight.sweat};

  --text-display: ${type.display};
  --text-display--line-height: ${leading.display};
  --text-h1: ${type.h1};
  --text-h1--line-height: ${leading.heading};
  --text-h2: ${type.h2};
  --text-h2--line-height: ${leading.heading};
  --text-h3: ${type.h3};
  --text-eyebrow: ${type.eyebrow};

  --shadow-long: ${shadow.long};
  --shadow-lift: ${shadow.lift};
}

/* shadcn indirection. Declared inline so the emitted utility keeps the var()
   reference and therefore respects the .theme-app scope override. */
@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);

  --font-display: var(--kk-font-display);
  --font-sans: var(--kk-font-sans);
  --font-mono: var(--kk-font-mono);

  --radius-sm: calc(var(--radius) - 8px);
  --radius-md: calc(var(--radius) - 4px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
  --radius-2xl: calc(var(--radius) + 10px);
}
`;
}

export function appCss(): string {
  const scoped: Record<string, string> = {
    '--background': app.background,
    '--foreground': app.textPrimary,
    '--card': app.surface,
    '--card-foreground': app.textPrimary,
    '--popover': app.surface,
    '--popover-foreground': app.textPrimary,
    '--primary': app.anchor,
    '--primary-foreground': '#FFFFFF',
    '--secondary': app.rowHover,
    '--secondary-foreground': app.textPrimary,
    '--muted': app.rowHover,
    '--muted-foreground': app.textSecondary,
    '--accent': app.rowHover,
    '--accent-foreground': app.textPrimary,
    '--destructive': brand.clay,
    '--destructive-foreground': '#FFFFFF',
    '--border': app.border,
    '--input': app.border,
    '--ring': app.accent,
    '--radius': `${radius.control}px`,
    '--sidebar': app.anchor,
    '--sidebar-foreground': '#EEF1F6',
    '--sidebar-primary': app.accent,
    '--sidebar-primary-foreground': '#FFFFFF',
    '--sidebar-accent': app.sidebarHover,
    '--sidebar-accent-foreground': '#FFFFFF',
    '--sidebar-border': brand.nightfall,
    '--sidebar-ring': app.accent,
    '--kk-text-muted': app.textMuted,
    ...statusVars,
  };

  return `${HEADER('app.css')}
/* The dashboard/admin system, scoped. Redefining the same custom properties under this
   class makes every Tailwind utility resolve to app values inside the wrapped subtree,
   and firstlight values everywhere else. Cream never enters this system. */
.theme-app {
${block(scoped)}
  font-family: var(--kk-font-sans);
  font-feature-settings: 'tnum';
  background: var(--background);
  color: var(--foreground);
}

/* Display type is a public-surface device. Inside the app, headings are the UI face at
   a heavier weight — a serif-ish display face hurts scanning in dense tables. The one
   exception is the wordmark in the top-left corner, which opts back in explicitly. */
.theme-app h1,
.theme-app h2,
.theme-app h3 {
  font-family: var(--kk-font-sans);
  letter-spacing: -0.01em;
}
`;
}
